#! /bin/sh
set -e

tag=${1:-latest}

echo "*** building tag $tag"

img=mcluseau/kingress:$tag

docker build -t $img .

if [ $tag == latest ]; then
  exit
fi

read -p "push?"
docker push $img

git commit -am "version $tag"
git tag -am $tag $tag

